### ISSUE TITLE
Python: Is CLI '--foo bar' the preferred standard in Python instead of '--foo=bar'?

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/port4me#37]
Is CLI `--foo bar` the preferred standard in Python instead of `--foo=bar`?  I see it used somewhere, but I'm not sure.  I definitely like the `--foo=bar` format, because it makes it non-amigous.  For instance, is:

```sh
python -m somepkg --foo bar
```

calling with boolean flag `--foo` and passing `bar` as an argument (e.g. a filename), or is the same as:

```sh
python -m somepkg --foo=bar
```

By sticking to only `--foo=bar` this 100% clear.

If we use `--foo=bar`, we should update the help to use that too:

```sh
$ python -m port4me --help
usage: python -m port4me [-h] [--tool TOOL] [--user USER] [--prepend PORTS] [--include PORTS] [--exclude PORTS] [--list N]
                         [--test PORT]

port4me: Get the Same, Personal, Free TCP Port over and over

options:
  -h, --help       show this help message and exit
  --tool TOOL      Used in the seed when generating port numbers, to get a different port sequence for different tools.
  --user USER      Used in the seed when generating port numbers. Defaults to determining the username with getuser().
  --prepend PORTS  A list of ports to try first
  --include PORTS  If specified, skip any ports not in this list
  --exclude PORTS  Skip any ports in this list
  --list N         Instead of returning a single port, return a list of this many ports without checking if they are free.
  --test PORT      If specified, return whether the port `PORT` is not in use. All other parameters will be ignored.
```

**Comment by Finnventor** [comment]
It seems like `--foo bar` is the standard, even though it's ambiguous. The argparse module (from the Python standard library) automatically creates the help text in `python -m port4me --help` from the `add_argument()` calls in `__main__.py`.

`python --help` also uses a space when describing its arguments:

    usage: python [option] ... [-c cmd | -m mod | file | -] [arg] ...
    Options (and corresponding environment variables):
    -b     : issue warnings about str(bytes_instance), str(bytearray_instance)
             and comparing bytes/bytearray with str. (-bb: issue errors)
    -B     : don't write .pyc files on import; also PYTHONDONTWRITEBYTECODE=x
    -c cmd : program passed in as string (terminates option list)

    ...

argparse supports either ` ` or `=`, so `python -m port4me --list=5` works, even though `python -m=port4me` doesn't.

**Comment by HenrikBengtsson** [comment]
> so `python -m port4me --list=5` works, even though `python -m=port4me` doesn't.

In think the `--NAME=VALUE` format is a GNU invention, and they call them "long-format options".  I think `-SYMBOL VALUE` is the original POSIX standard.   If you look at just those two "standards", then there should be no `-SYMBOL=VALUE`, i.e. it's not surprising that `-m=port4me` does not work.  For the same reason, `-list 5` or `-list=5` shouldn't work. (Of course, then there are things like Java that break these de-facto standards).

I can live with `--NAME VALUE`, unless there's a non-hackish way of disabling it.
