### ISSUE TITLE
Python: port4me(test=80) and port4me(test=443) return True on macOS - why?

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/port4me#59]
GitHub Actions checks for port 80 and port 443 says that they're available on macOS (only).  Why is this?  I don't have access to macOS, so I can only test via GitHub Actions.

```
    def test_port_80_is_reserved():
>       assert port4me(test=80) == False
E       assert True == False
E        +  where True = port4me(test=80)

python/tests/test_port4me.py:116: AssertionError
__________________________ test_port_443_is_reserved ___________________________

    def test_port_443_is_reserved():
>       assert port4me(test=443) == False
E       assert True == False
E        +  where True = port4me(test=443)
```

**Comment by Finnventor** [comment]
When outputting ports, the python implementation checks that it's in the [1024, 65536] range, so it is guaranteed to never suggest privileged ports (unless it's called with `port4me(min_port=1)` and port4me also has permission to open the port)
https://github.com/HenrikBengtsson/port4me/blob/a3ef7890d4ea1439dd8bef25ceeb58268463c0c8/python/port4me/__init__.py#L129C10-L129C10
but that doesn't happen for port4me(test=80) because that only checks if the port is accessible with `s.bind(("", port))`.

It looks like it's just that macOS doesn't have the restriction on who can open ports in that range:
https://developer.apple.com/forums/thread/674179

I'd say this is not a bug, unless we want `port4me(test=80)` to claim that all privileged ports are in use even if they aren't.
Maybe instead we should have a test with a second process that binds to the port and then checks whether port4me can see that it's in use.

**Comment by HenrikBengtsson** [comment]
> It looks like it's just that macOS doesn't have the restriction on who can open ports in that range: https://developer.apple.com/forums/thread/674179

Ah, TIL. That's interesting.

I added the same [checks for MS Windows](https://github.com/HenrikBengtsson/port4me/actions/runs/7404603216/job/20146356209#step:7:33), and it turns out that there, ports 22 and 443 can be bound, but not 80.  I think we need to:

* [x] read up on MS Windows TCP port rules too.

 
> I'd say this is not a bug, unless we want `port4me(test=80)` to claim that all privileged ports are in use even if they aren't. 

100% agree. This is not a bug. It was clearly my assumptions about ports 1-1023 requiring admin rights.

**Importantly**, we need to 

* [ ] decision whether to always exclude ports 1-1023 when searching for an available port to be consistent across operating systems
* [ ] document this decision

I think it's simpler if we aim for reproducible behavior across operating systems, which means we have to exclude ports 1-1023 regardless of them being available or not.

> Maybe instead we should have a test with a second process that binds to the port and then checks whether port4me can see that it's in use.

I actually added that before the above;

The Python tests:

https://github.com/HenrikBengtsson/port4me/blob/a3ef7890d4ea1439dd8bef25ceeb58268463c0c8/python/tests/test_port4me.py#L124-L130

The CLI API tests:

https://github.com/HenrikBengtsson/port4me/blob/a3ef7890d4ea1439dd8bef25ceeb58268463c0c8/python/tests/port4me.bats#L152-L154

and

https://github.com/HenrikBengtsson/port4me/blob/a3ef7890d4ea1439dd8bef25ceeb58268463c0c8/python/tests/incl/ports.sh#L90-L141

**Comment by HenrikBengtsson** [comment]
Turns out that a non-privileged user on MS Windows 10, can also bind ports in 1-1023, e.g.

```r
> port4me::port4me(test=80)
[1] TRUE
> port4me::port4me(test=22)
[1] TRUE
> port4me::port4me(test=443)
[1] TRUE
```

One proof that it works, is to launch the internal HTTP help server on port 80 as:

```r
> options(help.ports=80); port <- tools::startDynamicHelp(TRUE); port
starting httpd help server ... done
[1] 80
```
and we can confirm it's bound by:

```r
> port4me::port4me(test=80)
[1] FALSE
```

**Comment by HenrikBengtsson** [comment]
For the documentation: According to <https://developer.apple.com/forums/thread/674179>, support for binding to privileged ports 1-2023 was introduced in macOS Mojave.  This is the same as macOS 10.14 (2018-09-24).

**Comment by HenrikBengtsson** [comment]
I've updated the Bash, Python, and R tests such that they only run the port=80 test on Linux.

**Comment by HenrikBengtsson** [comment]
I'm closing this one, but I've created Issue #60, which is related to this.

**Comment by HenrikBengtsson** [comment]
Got another reference for the macOS behavior: 

"And in macOS 10.14 we removed the restriction on binding to low-number ports (r. 17427890)"

Source: https://developer.apple.com/forums/thread/708765

/ht @hrbrmstr (https://mastodon.social/@henrikbengtsson/111701295802596800)
