### ISSUE TITLE
Ports 1-1023: Make sure they can be sampled from via --include=<ports>

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/port4me#60]
On Linux, a non-privileged user cannot bind to ports 1-1023.  On macOS and MS Windows, they can. In order for **port4me** to produce reproducible results across platforms, it will only sample from ports 1024-65535.

That said, we should add optional support for drawing from all ports (1-65535).

Currently, the lower limit of 1024 is hard coded in a few places.  As a first step, we should identify all such hard-coded limits, and see if they can be replaced with something more flexible.

**Comment by Finnventor** [comment]
When I wrote the python implementation, I added `min_port=1024, max_port=65535` as the last two arguments in the port4me() function, so `min_port` can already be overridden in Python (I can rename these arguments if there's a different name that makes more sense). `max_port` can be decreased but not increased, because the LCG has 65537 as the modulus. I don't think that's a problem, since I don't know if there is an OS that supports higher ports, and in any case having 64,511 ports is more than enough to make collisions very rare (unless there's something that increases the chance of collisions due to a weird interaction between the usernames being lowercase ASCII, the hash function, and the LCG. Have we tested port4me on a large dataset of usernames to see how often collisions happen?)

We also might want to add environment variables to set defaults for these.

**Comment by HenrikBengtsson** [comment]
I've been thinking about this a bit more, and I _believe_ (to be validated) that we can use the _range_ of `--include=<ports>` (dropping ports in `--exclude=<ports>`) as the minimum and maximum ports to be used.

# Rationale

If we take a step back, we use the LCG algorithm to sample pseudo-random integers in $[0, m-1]$, where $m$ is the "modulo" parameters. We use $m = 2^{16} + 1$, so we get integers in $[0, 2^{16}]$ = $[0,65536]$ (sic!).  

Now, because our LCG parameters $(a, c, m) = (75, 74, 2^{16}+1)$, we have $(a-c) = 1$ and then the $s = m - 1$ state becomes _dead_ state (a state that cannot be left), so in that case we do $s = s + 1$ to get out of the dead state.  This means that we get integers in $[0, 2^{16}-1]$ = $[0,65535]$.  

The values generated by the LCG algorithm is _uniformly_ distributed over $[0,65535]$.

Next, if the LCG seed, which is our pseudo-random value, happens to fall outside of $[1024,65535]$, we choose to ignore it and ask for the next LCG seed.  Formally, we here use a [Acceptance-Rejection Sampling method](https://en.wikipedia.org/wiki/Rejection_sampling) to refine what values we draw from the original distribution.  The original distribution is uniform over $[0,65536]$, and this resampling method gives us a sample uniform over $[1024,65535]$.

Of course, we can use the same technique to draw uniformly from any set $[s,t]$, where $0 <= s < t <= 65535$.

Here, your `min_port` and `max_port` corresponds to $s$ and $t$, respectively.

Now, if we specify `--include=<include>` and `--exclude=<exclude>`, what we're effectively doing is _another_ round of resample on top of our (semi-)hard-coded $[1024,65535]$ distribution.

If we define $candidates$ as $candidates = include / exclude$ (= `setdiff(include, exclude)` speaking R), then we can use $min(candidates)$ and $max(candidates)$ as our upper- and lower-limits $s$ and $t$.  Point is, there's really no point of doing two rounds of resampling.  We can simply do one round, by defining $s = min(candidates)$ and $t = max(candidates)$, where our default is $include = \\{1024, ..., 65535\\}$ and $exclude = \\{\\}$.

**Comment by HenrikBengtsson** [comment]
I've now updated R and Bash, to use a helper function `lcg_port(min, max, subset)`, which internally draws a random port from `lcg()` until it falls within $[min,max]$, and if $subset$ is specified, also makes sure the port is within that subset.  This made the `port4me()` code a bit cleaner.

Arguments `min` and `max`, defaults to `min(subset)` and `max(subset)`, if `subset` is specified. Otherwise, to the 1024 and 65535 as usual.

I've added unit tests to R that validates that `lcg()` and `lcg_ports()` draw samples uniformly for different `min`, `max`, and `subset` specifications.

**Comment by HenrikBengtsson** [comment]
# Next action

* [x] Drop `min_port` and `max_port` from Python's `port4me()`.
* [ ] Have `min_port` and `max_port` respect min and max of `setdiff(include, exclude)`.

**Comment by HenrikBengtsson** [comment]
@Finnventor , could you have a look at this? What's left is basically to pull out min and max port from the set that include and exclude specify.

I think this is the last remaining task before the next release.

**Comment by HenrikBengtsson** [comment]
@Finnventor, thanks for the commit.  I've added/enabled a CLI test for this (commit 1c654c09).

Though, the reason why I get `min_port = min(subset)` and `max_port = max(subset)` upfront, is that then it's quick to check if the LCG-generated port is within [min_port, max_port].  That saves searching `subset` to see if it contains the proposed port or not, which should make it faster.  For the same reasons, I also don't set `include` to 1024-65535 by default, but just rely on [min_port, max_port].  This way the default only needs two comparisons per port candidate, rather than 65535-1024+1 comparisons.

**Comment by Finnventor** [comment]
Okay, I removed the min/max arguments, now the Python implementation only checks include/exclude. The minimum of 1024 is enforced through the default setting for include=1024-65535, and setting any custom include value overrides this (hopefully this matches the behavior you intended).

Also, about collisions/uniformity:
From my understanding, the LCG gives uniform output only when given random data as an input.
However, the seeds aren't uniformly distributed: Most seeds will be lowercase ASCII, so nearly every byte is `010XXXXX`, and vowels are more common. I think the question becomes, is our hash function correctly converting that into uniformly distributed seeds?

As a quick check, here's a histogram of port4me's output with the first username dataset I found:
https://github.com/danielmiessler/SecLists/blob/master/Usernames/xato-net-10-million-usernames.txt
![port4me_distribution](https://github.com/HenrikBengtsson/port4me/assets/50817575/0eb0acf5-2efc-41de-b75d-6b0d61ee40ca)

```
import matplotlib.pyplot as plt
from port4me import port4me

port_numbers = []

with open('xato-net-10-million-usernames.txt') as f:
    i = 0
    for line in f:
        port_numbers.append(port4me(user=line.strip()))
        if i % 100000 == 0:
            print(i, end='\r')
        i += 1
print(i)

plt.hist(port_numbers, bins='auto')
plt.xlabel('Port number')
plt.ylabel('Frequency')

plt.savefig('port4me_distribution.png')
plt.show()
```

(I recommend short-circuiting `is_port_free` and `get_env_ports` to save time when running this test.)

**Comment by HenrikBengtsson** [comment]
> Okay, I removed the min/max arguments, now the Python implementation only checks include/exclude. The minimum of 1024 is enforced through the default setting for include=1024-65535, and setting any custom include value overrides this (hopefully this matches the behavior you intended).

Yes, behavior is as expected. I was just thinking about the performance.

> Also, about collisions/uniformity:
> As a quick check, here's a histogram of port4me's output with the first username dataset I found: ...

Great work. Thanks for this. Could you please open a separate issue on this part?

**Comment by Finnventor** [comment]
Oops, I didn't see your reply yet when I wrote that first long message.

Using the `in` operator on Python's range() is fast because range only makes a fake list which generates values on demand, and they overrode `__contains__()` (which is what `in` uses behind the scenes) so it just makes a simple comparison with the start and end values. The default `port4me()` and `port4me(include=range(2000, 3001))` should both only make 2 comparisons per candidate.

If we need performance optimization in the case of port4me(include="2000-3000"), I could update parse_ports and include/exclude to work with a list of ranges and integers (currently it creates a list of integers only), but I don't think this will matter much since `python -m port4me --include=2000-3000` is already practically instantaneous.

**Comment by HenrikBengtsson** [comment]
> ... range only makes a fake list which generates values on demand

That's neat. R can do something similar since a few years, but never looked if they've implemented it for the "in" operator.

Sure, if you don't think it matters, let's keep it simple.

**Comment by HenrikBengtsson** [comment]
Closing. If we find we need to speed things up further, we can always revisit.
