### ISSUE TITLE
Python: --prepend=<set> should always be considered regardless of include and exclude

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/port4me#70]
@Finnventor , assuming all ports are available, we should get port 2000 when doing:

```sh
$ port4me --user=alice --prepend=2000-2009 --include=3000-3100
2000

$ Rscript -e port4me::port4me --user=alice --prepend=2000-2009 --include=3000-3100
2000
```

However, the current Python implementation does not consider the "prepend" set, because it's not part of the "include" set;

```sh
$ python -m port4me --user=alice --prepend=2000-2009 --include=3000-3100
3048
```

Basically, `--include=<set>` and `--exclude=<set>` only apply after `--prepend=<set>` has been exhausted.

I have a CLI test ready for this, which is how I caught it;

https://github.com/HenrikBengtsson/port4me/blob/1c654c09caab6749573d9f0755ca33ff5c9f5d4a/bash/tests/port4me.bats#L128-L134

**Comment by Finnventor** [comment]
Okay, I didn't know that prepend was supposed to have priority over include, I've fixed that now.

**Comment by HenrikBengtsson** [comment]
Thanks. I've added the CLI tests.
