### ISSUE TITLE
macOS compilation errors for specific setups(?)

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/port4me#74]
Creating an issue of PR #73 , so it's not forgotten.

# Issue

Installing **port4me** 0.7.0 on a macOS gives:

```sh
/opt/local/bin/gcc-mp-13 -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isystem/opt/local/include/LegacySupport -I/opt/local/include    -fPIC  -pipe -Os -arch ppc  -c 000.init.c -o 000.init.o
/opt/local/bin/gcc-mp-13 -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isystem/opt/local/include/LegacySupport -I/opt/local/include    -fPIC  -pipe -Os -arch ppc  -c test_tcp_port.c -o test_tcp_port.o
In file included from /usr/include/ppc/endian.h:121,
                 from /usr/include/machine/endian.h:35,
                 from /usr/include/netinet/in.h:90,
                 from test_tcp_port.c:8:
test_tcp_port.c: In function 'test_tcp_port':
test_tcp_port.c:18:37: error: 'u_int32_t' undeclared (first use in this function); did you mean 'uint32_t'?
   18 |   serv_addr.sin_addr.s_addr = htonl(INADDR_ANY);  // all available interfaces
      |                                     ^~~~~~~~~~
test_tcp_port.c:18:37: note: each undeclared identifier is reported only once for each function it appears in
test_tcp_port.c:18:37: error: expected ')' before numeric constant
   18 |   serv_addr.sin_addr.s_addr = htonl(INADDR_ANY);  // all available interfaces
      |                                     ^~~~~~~~~~
test_tcp_port.c:18:31: note: to match this '('
   18 |   serv_addr.sin_addr.s_addr = htonl(INADDR_ANY);  // all available interfaces
      |                               ^~~~~
make: *** [test_tcp_port.o] Error 1
ERROR: compilation failed for package ‘port4me’
```

This is with:

```
* using R version 4.3.2 (2023-10-31)
* using platform: powerpc-apple-darwin10.0.0d2 (32-bit)
* R was compiled by
    gcc-mp-13 (MacPorts gcc13 13.2.0_4+stdlib_flag) 13.2.0
    GNU Fortran (MacPorts gcc12 12.3.0_3+stdlib_flag) 12.3.0
* running under: OS X Snow Leopard 10.6
```

# Reproducibility

This problem does _not_ appear on:

* CRAN: https://cran.r-project.org/web/checks/check_results_port4me.html
* mac-builder: https://mac.r-project.org/macbuilder/submit.html
* GitHub Actions: https://github.com/HenrikBengtsson/port4me/actions/workflows/check-r.yml

On CRAN, they're testing with:

```
* using R version 4.3.1 (2023-06-16)
* using platform: aarch64-apple-darwin20 (64-bit)
* R was compiled by
    Apple clang version 14.0.0 (clang-1400.0.29.202)
    GNU Fortran (GCC) 12.2.0
* running under: macOS Ventura 13.4
```

and

```
* using R version 4.3.0 (2023-04-21)
* using platform: x86_64-apple-darwin20 (64-bit)
* R was compiled by
    Apple clang version 14.0.3 (clang-1403.0.22.14.1)
    GNU Fortran (GCC) 12.2.0
* running under: macOS Ventura 13.3.1
```

On GitHub Actions, `R CMD check --as-cran` on macOS does _not_ give these errors. There, we're running on:

```
* using R Under development (unstable) (2024-01-16 r85808)
* using platform: x86_64-apple-darwin20
* R was compiled by
    Apple clang version 14.0.0 (clang-1400.0.29.202)
    GNU Fortran (GCC) 12.2.0
* running under: macOS Monterey 12.7.2
```

and

```
* using R version 4.3.2 (2023-10-31)
* using platform: x86_64-apple-darwin20 (64-bit)
* R was compiled by
    Apple clang version 14.0.0 (clang-1400.0.29.202)
    GNU Fortran (GCC) 12.2.0
* running under: macOS Monterey 12.7.2
```

# Actions

* [ ] Can we reproduce this on GitHub Actions? Is that possible?
* [ ] Is this specific to PowerPC or specific versions of clang or GCC?
* [x] How to best make sure PR #73 does not break things for other macOS setups?

/ht @barracuda156

**Comment by barracuda156** [comment]
@HenrikBengtsson Yes, as I said in the PR, there is no problem with your code at all, but on some versions of macOS the build gonna fail due to a types mismatch. I cannot realistically determine exact subset of systems affected. However it seems that my patch works equally well for the latest macOS (i.e. it breaks nothing but fixes something).

**Comment by HenrikBengtsson** [comment]
Thanks, it's helpful to know what you also know (and don't know).

Just in case, could you please try with:

```c
#ifdef __APPLE__
  #ifndef u_int32_t
    typedef uint32_t u_int32_t;
  #endif
#endif
```

?  That could also somewhat clarify for future readers _when_ and _why_ that's done.

**Comment by barracuda156** [comment]
@HenrikBengtsson Yes, your suggestion works nicely and is preferable. I have rebased the PR.

**Comment by HenrikBengtsson** [comment]
Merged. Thanks for reaching out and thanks for all your work on making R run on more platforms.

**Comment by HenrikBengtsson** [comment]
Btw, the curl package has a very similar implementation (https://github.com/jeroen/curl/blob/master/src/findport.c). Maybe they need the same patch.

**Comment by barracuda156** [comment]
> Btw, the curl package has a very similar implementation (https://github.com/jeroen/curl/blob/master/src/findport.c). Maybe they need the same patch.

As of now, there is no issue with `R-curl`, whether on my PowerPC system (it builds without any patches from our side) or on Intel buildbots for older macOS.
I did encounter the similar problem at least once though, with an unrelated to R port.

**Comment by HenrikBengtsson** [comment]
> As of now, there is no issue with R-curl, whether on my PowerPC system (it builds without any patches from our side) or on Intel buildbots for older macOS.

Interesting. Then, I guess `u_int32_t` is defined in one of the includes that we don't use here.
